function plotOutcomePredictionResult_AllBiomarkers(predictionAllBiomarkers)

    close all;
    predictionDataT = round([predictionAllBiomarkers{1,2:4}; predictionAllBiomarkers{2,2:4}; predictionAllBiomarkers{3,2:4}]*100);
    predictionData = predictionDataT;
    
    legendStr = {predictionAllBiomarkers{1,1}; predictionAllBiomarkers{2,1}; predictionAllBiomarkers{3,1}};
    legendStr = strrep(legendStr, 'Vals', '');
    legendStr = strrep(legendStr, '_', '');
    legendStr = strrep(legendStr, 'ia', 'IES');
    
    labels = {'Sensitivity (%)', 'Specificity (%)', 'Accuracy (%)'};
    axesLimits = repmat([0;100],1,3);
    
    spider_plot_R2019b(predictionData,...
                        'AxesLabels', labels,...
                        'AxesInterval', 10,...
                        'AxesPrecision', 2, ...
                        'AxesLimits', axesLimits,...
                        'AxesLabelsOffset', 0.1,...
                        'AxesDisplay', 'one',...
                        'AxesLabelsEdge', 'none',...
                        'AxesFontSize', 12,...
                        'FillOption', {'on', 'on', 'on'},...
                        'FillTransparency', [0.4, 0.3, 0.2],...
                        'MarkerSize', 100,...
                        'AxesFontSize', 14,...
                        'LabelFontSize', 18);
    legend(legendStr, 'Location', 'northeastoutside', 'FontSize', 20);
    title('Outcome Prediction Results','FontSize',20);
    
end